/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Design system tokens
        "ds-primary": "#0F172A",
        "ds-primary-light": "#1E293B",
        "ds-accent": "#06B6D4",
        "ds-accent-light": "#67E8F9",
        "ds-accent-dark": "#0E7490",
        "ds-gaoxin": "#10B981",
        "ds-zhuanjing": "#F59E0B",
        "ds-financing": "#8B5CF6",
        "ds-combined": "#EC4899",
        "ds-success": "#22C55E",
        "ds-warning": "#F59E0B",
        "ds-danger": "#EF4444",
        "ds-info": "#3B82F6",
        "ds-bg-primary": "#F8FAFC",
        "ds-bg-card": "#FFFFFF",
        "ds-bg-elevated": "#F1F5F9",
        "ds-border": "#E2E8F0",
        "ds-border-subtle": "#F1F5F9",
        "ds-text-primary": "#0F172A",
        "ds-text-secondary": "#475569",
        "ds-text-tertiary": "#94A3B8",
      },
      fontFamily: {
        sans: ['"Noto Sans SC"', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      spacing: {
        "ds-1": "4px",
        "ds-2": "8px",
        "ds-3": "12px",
        "ds-4": "16px",
        "ds-5": "20px",
        "ds-6": "24px",
        "ds-8": "32px",
        "ds-10": "40px",
        "ds-12": "48px",
      },
      fontSize: {
        "ds-h1": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "ds-h2": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "ds-h3": ["18px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "ds-h4": ["15px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "600" }],
        "ds-body": ["14px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "ds-small": ["13px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "ds-caption": ["12px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" }],
        "ds-badge": ["11px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "ds-stat": ["36px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "ds-stat-label": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
      },
      maxWidth: {
        "ds-content": "1440px",
      },
      zIndex: {
        "sticky": "10",
        "overlay": "20",
        "modal": "30",
        "toast": "40",
        "top": "50",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "ds-card": "0 1px 3px 0 rgb(0 0 0 / 0.05), 0 1px 2px -1px rgb(0 0 0 / 0.05)",
        "ds-card-hover": "0 10px 30px -5px rgba(0, 0, 0, 0.08), 0 4px 10px -5px rgba(0, 0, 0, 0.04)",
        "ds-toast": "0 10px 40px rgba(0,0,0,0.12)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-4px)" },
          "50%": { transform: "translateX(4px)" },
          "75%": { transform: "translateX(-4px)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(6, 182, 212, 0)" },
          "50%": { boxShadow: "0 0 12px 2px rgba(6, 182, 212, 0.2)" },
        },
        "spinner": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "count-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "skeleton": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(20px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "dot-pulse": {
          "0%, 100%": { opacity: "0.3", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.3)" },
        },
        "pop-in": {
          "0%": { transform: "scale(0.5)", opacity: "0" },
          "70%": { transform: "scale(1.1)", opacity: "1" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "shake": "shake 0.4s ease-in-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "spinner": "spinner 0.8s linear infinite",
        "count-up": "count-up 0.3s ease-out",
        "skeleton": "skeleton 1.5s ease-in-out infinite",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "dot-pulse": "dot-pulse 2s ease-in-out infinite",
        "pop-in": "pop-in 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionTimingFunction: {
        "ds-primary": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
